<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_inputEmail</name>
   <tag></tag>
   <elementGuidId>de85bdab-6f0b-4e72-80ca-b999e2e97a8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a66d60a-c003-431b-8d51-a8d89ef99347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>a53cf696-556f-44c3-9b41-c2eb73514bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>229dc29e-d4e3-4bf0-b9c3-7fb5c5f66c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmail</value>
      <webElementGuid>bcdd342d-5ba7-49ad-8bd0-78a1e25b5f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>inputEmail</value>
      <webElementGuid>52904589-267d-4bbb-ba1b-b17b0904c564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>d8760cdd-e24d-42da-9572-dd313230d2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>9354bfca-e16a-4562-acb5-920ec1cea555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmail&quot;)</value>
      <webElementGuid>aa7ec2e9-9436-46ad-932b-1160f0c6da21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputEmail']</value>
      <webElementGuid>f1048bc2-767c-4de1-a066-3e32ecaa2f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/div[2]/div/input</value>
      <webElementGuid>18e4ebaa-1b36-4f6e-8767-b723eafb3188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>19d0b133-2cd9-4035-883b-c7742b92eba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'inputEmail' and @name = 'inputEmail' and @placeholder = 'Email']</value>
      <webElementGuid>adfd0ff8-8014-4264-a656-b9526f5ff654</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
